### ISSUE TITLE
Different Architectures for COCO dataset and PASCAL VOC Dataset

### ISSUE THREAD

**Issue by iremonur** [hero-y/BHRL#11]
There is a difference between the model configurations provided for PASCAL VOC and COCO datasets in BHRLRoIHead
In VOC configuration:

roi_layer=dict(
    type='DeformRoIPoolPack',
    output_size=7,
    output_channels=256),

In COCO configuration:

roi_layer=dict(type='RoIAlign', out_size=7, sampling_ratio=0),

What is the reason for this difference between architectures?

I would be glad if you help me with this.

**Comment by hero-y** [comment]
The config for roi_layer is optional.
