### ISSUE TITLE
Class predictions

### ISSUE THREAD

**Issue by iremonur** [hero-y/BHRL#4]
Hello, thank you for the code! I am trying to understand the model outputs by running the test code on the Pascal VOC dataset.  
The model outputs the "result" variable in line 35 in the tools/test.py as below:
result = model(return_loss=False, rescale=True, **data)
Here, the model outputs an array dimension of 5: the BBOX coordinates, and classification scores. But I couldn't find the class labels predicted by the model.
Where the model outputs the predicted class labels? 
I would be glad if you help me with this!

**Comment by hero-y** [comment]
It is a two-classification task, the classification score represents the probability that the detected object and template category are the same.

**Comment by iremonur** [comment]
Thank you very much!
