### ISSUE TITLE
Details on the ref_ann_file

### ISSUE THREAD

**Issue by saswat0** [hero-y/BHRL#5]
Hi @hero-y 

Could you please explain the use/significance of this ref_ann_file file? How may this be created for different datasets and how to tweak it for different settings?

**Comment by hero-y** [comment]
For coco, the ref_ann_file is used to generate the query patch (template). You can see the paragraph "Generating target and query pairs" in "One-Shot Object Detection with Co-Attention and Co-Excitation" for details.

**Comment by saswat0** [comment]
In that case, if query images are sourced externally (i.e., they belong to another dataset), how can this training run?

**Comment by hero-y** [comment]
I didn't try it, but I guess it can run.
